tasks:
  - name: tools
    before : 
            sudo apt-get install tree
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT:  on-partial
    before: 
              ./bin/aws-cli-install
  - name: terraform
    before: 
              ./bin/terraform-install