tasks:
  - name: tools
    before : 
            chmod +x bin/*
            sudo apt-get install tree
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT:  on-partial
    before: 
              ./bin/aws-cli-install
    command: echo""AWS CLI installed"
  - name: terraform
    before: 
              ./bin/terraform-install
    command: echo"Terraform installed"